spring.application.name=AuthenticationBackend


spring.datasource.username=student
spring.datasource.password=25050032
spring.datasource.url=jdbc:postgresql://localhost:5432/AuthBackendDb
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true

springdoc.paths-to-match=/api/v1/**
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.github.bgrebennikov.authenticationbackend.controller
